In [2]:
import pandas as pd
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from spotipy.oauth2 import SpotifyOAuth
import requests
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import tensorflow as tf
from dotenv import load_dotenv
import os 

In [3]:
mood1 = pd.read_csv('MusicMoodFinal.csv')
# mood2 = pd.read_csv('278k_song_labelled.csv')

In [ ]:
mood1.sample(5)

In [ ]:
# import spotipy
# from spotipy.oauth2 import SpotifyClientCredentials
# import time
# import pandas as pd



# def fetch_tracks_by_genre_year(start_year, end_year, genres=None):
#     """
#     Fetch tracks grouped by year, genre, and title - returns distinct records only
#     """
#     if genres is None:
#         genres = [
#             'pop', 'rock', 'hip-hop', 'electronic', 'indie',
#             'r-and-b', 'country', 'latin', 'k-pop', 'metal',
#             'dance', 'soul', 'reggae', 'jazz', 'alternative',
#             'folk', 'blues', 'punk', 'funk', 'trap'
#         ]
    
#     tracks_set = set()  # Store unique combinations
#     tracks_list = []
    
#     total_years = end_year - start_year + 1
#     total_genres = len(genres)
#     current = 0
    
#     print(f"Fetching {total_years} years × {total_genres} genres = {total_years * total_genres} search combinations\n")
    
#     for genre in genres:
#         for year in range(start_year, end_year + 1):
#             current += 1
#             print(f"[{current}/{total_years * total_genres}] Genre: {genre:15} | Year: {year}", end=" | ")
            
#             offset = 0
#             year_genre_count = 0
            
#             while offset < 2000:
#                 try:
#                     query = f"genre:{genre} year:{year}"
#                     response = sp.search(
#                         q=query,
#                         type="track",
#                         limit=50,
#                         offset=offset
#                     )
                    
#                     results = response['tracks']['items']
#                     if not results:
#                         break
                    
#                     for track in results:
#                         try:
#                             # Extract genres from audio features
#                             track_name = track['name']
#                             artist_name = track['artists'][0]['name'] if track['artists'] else 'Unknown'
#                             release_date = track['album']['release_date']
                            
#                             # Parse year from release date
#                             try:
#                                 track_year = int(release_date.split('-')[0])
#                             except:
#                                 track_year = year
                            
#                             # Create unique key: (year, genre, title)
#                             unique_key = (track_year, genre, track_name.lower().strip())
                            
#                             if unique_key not in tracks_set:
#                                 tracks_set.add(unique_key)
#                                 tracks_list.append({
#                                     'year': track_year,
#                                     'title': track_name,
#                                     'artist': artist_name,
#                                     'genre': genre,
#                                     'release_date': release_date,
#                                     'track_id': track['id'],
#                                     'popularity': track.get('popularity', 0)
#                                 })
#                                 year_genre_count += 1
#                         except Exception as e:
#                             pass
                    
#                     if len(results) < 50:
#                         break
                    
#                     offset += 50
#                     time.sleep(0.15)
                    
#                 except spotipy.exceptions.SpotifyException as e:
#                     if e.http_status == 429:
#                         print("Rate limited, waiting 30s...", end="")
#                         time.sleep(30)
#                     break
#                 except Exception as e:
#                     break
            
#             print(f"Found {year_genre_count} distinct tracks")
    
#     return tracks_list


# def get_distinct_tracks(start_year, end_year, genres=None):
#     """
#     Get distinct tracks by year, title, and genre
#     """
#     tracks = fetch_tracks_by_genre_year(start_year, end_year, genres)
    
#     # Convert to DataFrame for easier manipulation
#     df = pd.DataFrame(tracks)
    
#     # Select distinct by year, title, genre (keep first occurrence)
#     df_distinct = df.drop_duplicates(subset=['year', 'title', 'genre'], keep='first')
    
#     # Sort by year, genre, title
#     df_distinct = df_distinct.sort_values(['year', 'genre', 'title'])
    
#     print(f"\n{'='*80}")
#     print(f"DISTINCT TRACKS: {len(df_distinct)} unique (year, genre, title) combinations")
#     print(f"Total records fetched: {len(df)}")
#     print(f"Duplicates removed: {len(df) - len(df_distinct)}")
#     print(f"{'='*80}\n")
    
#     return df_distinct


# def display_summary(df):
#     """
#     Display summary statistics
#     """
#     print("SUMMARY BY YEAR:")
#     print(df.groupby('year').size())
    
#     print("\n\nSUMMARY BY GENRE:")
#     print(df.groupby('genre').size().sort_values(ascending=False))
    
#     print("\n\nSUMMARY BY YEAR & GENRE (Top 10):")
#     print(df.groupby(['year', 'genre']).size().sort_values(ascending=False).head(10))


# # Run the fetcher
# print("Starting Spotify track extraction (Distinct by Year, Genre, Title)...\n")

# df_tracks = get_distinct_tracks(2021, 2025)

# # Display summary
# display_summary(df_tracks)

# # Save to CSV
# csv_file = 'spotify_tracks_distinct_2021_2025.csv'
# df_tracks.to_csv(csv_file, index=False)
# print(f"\n✓ Saved to {csv_file}")

# # Display sample records
# print(f"\n\nSAMPLE RECORDS (First 15):")
# print("="*80)
# print(df_tracks[['year', 'title', 'artist', 'genre', 'release_date']].head(15).to_string(index=False))

# # SQL-like query examples
# print(f"\n\nQUERY EXAMPLES:")
# print("="*80)

# print("\n1. Tracks from 2024, Pop genre:")
# print(df_tracks[(df_tracks['year'] == 2024) & (df_tracks['genre'] == 'pop')][['title', 'artist', 'release_date']].head(10).to_string(index=False))

# print("\n2. Top 5 genres by track count (2021-2025):")
# print(df_tracks['genre'].value_counts().head(5))

# print("\n3. Most popular artists (2021-2025):")
# print(df_tracks['artist'].value_counts().head(10))

In [ ]:
spotifynew_df = pd.read_csv('spotify_tracks_distinct_2021_2025.csv')

In [ ]:
spotifynew_df.drop(columns=['popularity'], inplace=True) 

In [ ]:
spotifynew_df.head()

In [4]:
mood1.isnull().sum()

id                   0
name                71
popularity           0
duration_ms          0
explicit             0
artists              0
id_artists           0
release_date         0
danceability         0
energy               0
key                  0
loudness             0
mode                 0
speechiness          0
acousticness         0
instrumentalness     0
liveness             0
valence              0
tempo                0
time_signature       0
Mood                 0
dtype: int64

In [5]:
cleaned_mood1 = mood1.dropna(subset=['name'])

In [6]:
cleaned_mood1.isnull().sum()

id                  0
name                0
popularity          0
duration_ms         0
explicit            0
artists             0
id_artists          0
release_date        0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
Mood                0
dtype: int64

In [7]:
mood_mapping = {
    'Calm': 0,
    'Happy': 1,
    'Sad': 2,
    'Energetic': 3
}

# Apply the mapping to the 'Mood' column
mood1['Mood'] = mood1['Mood'].map(mood_mapping)

# Verify the transformation
mood1[['Mood']].head()

Mood
0     0
1     1
2     2
3     0
4     2

In [8]:
from sklearn.preprocessing import StandardScaler
import sklearn
import numpy as np

features_data = mood1.drop(columns=['Mood'])
numeric_features_data = features_data.select_dtypes(include=['float64', 'int64'])

# Scale only the numeric features
scaler = StandardScaler()
scaled_features = scaler.fit_transform(numeric_features_data)

# Convert the scaled features back to a DataFrame for easier handling
scaled_features_df = pd.DataFrame(scaled_features, columns=numeric_features_data.columns)

# Display the first few rows of the scaled features
scaled_features_df.head()

popularity  duration_ms  explicit  danceability    energy       key  \
0   -1.174160    -0.815233 -0.214754      0.490096 -0.385182 -1.483654   
1   -1.500768    -1.042088 -0.214754      0.791115 -1.107625 -1.483654   
2   -1.500768    -0.382618 -0.214754     -0.780204 -1.449000 -1.199517   
3   -1.500768    -0.420026 -0.214754     -1.460507 -1.776084  0.505310   
4   -1.500768    -0.529308 -0.214754     -0.972856 -1.524420 -0.631241   

   loudness      mode  speechiness  acousticness  instrumentalness  liveness  \
0 -0.615393  0.719665     1.924128      0.642528          2.362779 -0.341434   
1 -2.344110  0.719665     4.736917      0.995129         -0.425120 -0.357710   
2 -2.156266  0.719665    -0.298309      1.559864         -0.343432 -0.010498   
3 -3.488663  0.719665    -0.302756      1.562730          3.014787 -0.596418   
4 -1.315289 -1.389536    -0.366127      1.545530          0.062013  0.526596   

    valence     tempo  time_signature  
0 -1.650527 -0.457392       -1.845842  
1  0.398600 -0.552876       -6.072724  
2 -0.369823  0.401596        2.381040  
3 -0.602678  1.730782       -1.845842  
4 -1.382743 -0.512190        0.267599

In [9]:
features_to_drop = ['popularity', 'explicit', 'mode', 'key', 'time_signature','duration_ms']
features_data = features_data.drop(columns=features_to_drop)

In [10]:
features_data.head()

id                                 name  \
0  35iwgR4jXetI318WEWsa1Q                                Carve   
1  021ht4sdgPcrDgSk7JTbKY  Capítulo 2.16 - Banquero Anarquista   
2  07A5yehtSnoedViJAZkNnc   Vivo para Quererte - Remasterizado   
3  08FmqUhxtyLTn6pAh6bk45        El Prisionero - Remasterizado   
4  08y9GfoqCWfOGsKdwojr5e                  Lady of the Evening   

               artists                  id_artists release_date  danceability  \
0              ['Uli']  ['45tIt06XoI0Iio4LBEVpls']   1922-02-22         0.645   
1  ['Fernando Pessoa']  ['14jtPCOoNZwquk5wd9DxrY']   1922-06-01         0.695   
2  ['Ignacio Corsini']  ['5LiOoJbxVSAMkBS2fUm3X2']   1922-03-21         0.434   
3  ['Ignacio Corsini']  ['5LiOoJbxVSAMkBS2fUm3X2']   1922-03-21         0.321   
4      ['Dick Haymes']  ['3BiJGZsyX9sJchTqcSA7Su']         1922         0.402   

   energy  loudness  speechiness  acousticness  instrumentalness  liveness  \
0  0.4450   -13.338       0.4510         0.674            0.7440     0.151   
1  0.2630   -22.136       0.9570         0.797            0.0000     0.148   
2  0.1770   -21.180       0.0512         0.994            0.0218     0.212   
3  0.0946   -27.961       0.0504         0.995            0.9180     0.104   
4  0.1580   -16.900       0.0390         0.989            0.1300     0.311   

   valence    tempo  
0    0.127  104.851  
1    0.655  102.009  
2    0.457  130.418  
3    0.397  169.980  
4    0.196  103.220

In [11]:
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features_data.select_dtypes(include=['float64', 'int64']))
target = mood1['Mood']

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
X_train, X_test, y_train, y_test = train_test_split(scaled_features,target, test_size=0.2, random_state=42)

In [13]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 6. Prediction
y_pred = model.predict(X_test)

In [14]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.9692


In [15]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      8203
           1       0.96      0.95      0.95     30541
           2       0.98      0.98      0.98     42417
           3       0.97      0.97      0.97     36174

    accuracy                           0.97    117335
   macro avg       0.97      0.97      0.97    117335
weighted avg       0.97      0.97      0.97    117335



In [16]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Confusion Matrix:
[[ 8061    13   129     0]
 [    4 29065   515   957]
 [  132   432 41546   307]
 [    1   838   289 35046]]


In [17]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from scipy.stats import randint

# Define the parameter distribution for Random Forest
param_dist = {
    'n_estimators': randint(100, 500),  # Random number of trees between 100 and 500
    'max_depth': [None, 10, 20, 30, 40],  # Max depth of the trees
    'min_samples_split': randint(2, 10),  # Minimum samples required to split a node
    'min_samples_leaf': randint(1, 10),  # Minimum samples required at a leaf node
    'max_features': ['auto', 'sqrt', 'log2'],  # Number of features to consider at each split
    'random_state': [42]
}

# Initialize RandomForestClassifier
rf = RandomForestClassifier()

# Set up RandomizedSearchCV
random_search = RandomizedSearchCV(estimator=rf, param_distributions=param_dist, 
                                   n_iter=10, cv=3, n_jobs=-1, verbose=2, scoring='accuracy', random_state=42)

# Fit the RandomizedSearchCV to the data
random_search.fit(X_train, y_train)

# Best parameters found
print(f"Best parameters found: {random_search.best_params_}")

# Best model from random search
best_rf_model = random_search.best_estimator_

# Predict using the best model
y_pred_best = best_rf_model.predict(X_test)

# Evaluate the model's performance
accuracy_best = accuracy_score(y_test, y_pred_best)
print(f"Accuracy of tuned model: {accuracy_best:.4f}")

# Classification Report
print("\nClassification Report for Tuned Model:")
print(classification_report(y_test, y_pred_best))

# Confusion Matrix for the tuned model
print("\nConfusion Matrix for Tuned Model:")
print(confusion_matrix(y_test, y_pred_best))


Fitting 3 folds for each of 10 candidates, totalling 30 fits


c:\Users\acer\Downloads\Spotigai\venv\lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
15 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
6 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\acer\Downloads\Spotigai\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\acer\Downloads\Spotigai\venv\lib\site-packages\sklearn\base.py", line 1145, in wrapper
    estimator._validate_params()
  File "c:\Users\acer\Downloads\Spotigai\venv\lib\site-packages\sklearn\base.py", line 638, in _validate_params
    validate_parameter_constraints(


Best parameters found: {'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 3, 'n_estimators': 364, 'random_state': 42}
Accuracy of tuned model: 0.9697

Classification Report for Tuned Model:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      8203
           1       0.96      0.95      0.96     30541
           2       0.98      0.98      0.98     42417
           3       0.97      0.97      0.97     36174

    accuracy                           0.97    117335
   macro avg       0.97      0.97      0.97    117335
weighted avg       0.97      0.97      0.97    117335


Confusion Matrix for Tuned Model:
[[ 8050    13   139     1]
 [    6 29065   530   940]
 [  125   429 41545   318]
 [    1   781   278 35114]]


In [19]:
import joblib

# The model you trained with RandomizedSearchCV
model_to_save = best_rf_model 
filename = 'random_forest_mood_model_update.joblib'

# Save the model to a file
joblib.dump(model_to_save, filename)

print(f"✅ Model saved successfully to {filename}")

✅ Model saved successfully to random_forest_mood_model_update.joblib
